import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
import { LOAN_STATUSES } from '../constants/index.js';

export const LoanProduct = sequelize.define('LoanProduct', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  organizationId: { type: DataTypes.UUID, allowNull: false },
  name: { type: DataTypes.STRING(100), allowNull: false },
  code: { type: DataTypes.STRING(20), allowNull: false },
  type: {
    type: DataTypes.ENUM('emergency', 'development', 'school_fees', 'business', 'asset_financing', 'personal'),
    allowNull: false,
  },
  interestRate: { type: DataTypes.DECIMAL(5, 2), allowNull: false },
  interestMethod: { type: DataTypes.ENUM('flat', 'reducing_balance'), defaultValue: 'reducing_balance' },
  minAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false },
  maxAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false },
  minTermMonths: { type: DataTypes.INTEGER, allowNull: false },
  maxTermMonths: { type: DataTypes.INTEGER, allowNull: false },
  processingFeePercent: { type: DataTypes.DECIMAL(5, 2), defaultValue: 0 },
  insuranceFeePercent: { type: DataTypes.DECIMAL(5, 2), defaultValue: 0 },
  penaltyRate: { type: DataTypes.DECIMAL(5, 2), defaultValue: 0 },
  gracePeriodDays: { type: DataTypes.INTEGER, defaultValue: 0 },
  requiresGuarantor: { type: DataTypes.BOOLEAN, defaultValue: true },
  minGuarantors: { type: DataTypes.INTEGER, defaultValue: 1 },
  multiplierOfSavings: { type: DataTypes.DECIMAL(5, 2), defaultValue: 3 },
  isActive: { type: DataTypes.BOOLEAN, defaultValue: true },
}, {
  tableName: 'loan_products',
  paranoid: true,
});

export const Loan = sequelize.define('Loan', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  organizationId: { type: DataTypes.UUID, allowNull: false },
  branchId: { type: DataTypes.UUID, allowNull: false },
  memberId: { type: DataTypes.UUID, allowNull: false, references: { model: 'members', key: 'id' } },
  loanProductId: { type: DataTypes.UUID, allowNull: false },
  loanNumber: { type: DataTypes.STRING(30), allowNull: false },
  type: { type: DataTypes.STRING(50), allowNull: false },
  principalAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false },
  interestRate: { type: DataTypes.DECIMAL(5, 2), allowNull: false },
  interestMethod: { type: DataTypes.ENUM('flat', 'reducing_balance'), defaultValue: 'reducing_balance' },
  termMonths: { type: DataTypes.INTEGER, allowNull: false },
  processingFee: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  insuranceFee: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  totalInterest: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  totalRepayable: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  monthlyInstallment: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  principalBalance: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  interestBalance: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  penaltiesBalance: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  totalPaid: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  purpose: DataTypes.TEXT,
  status: { type: DataTypes.ENUM(...Object.values(LOAN_STATUSES)), defaultValue: LOAN_STATUSES.PENDING },
  applicationDate: { type: DataTypes.DATEONLY, defaultValue: DataTypes.NOW },
  approvedAt: DataTypes.DATE,
  approvedBy: DataTypes.UUID,
  rejectedAt: DataTypes.DATE,
  rejectedBy: DataTypes.UUID,
  rejectionReason: DataTypes.TEXT,
  disbursedAt: DataTypes.DATE,
  disbursedBy: DataTypes.UUID,
  disbursementMethod: DataTypes.ENUM('cash', 'mpesa', 'bank_transfer', 'account_credit'),
  disbursementReference: DataTypes.STRING(100),
  firstRepaymentDate: DataTypes.DATEONLY,
  lastRepaymentDate: DataTypes.DATEONLY,
  closedAt: DataTypes.DATE,
  closedBy: DataTypes.UUID,
  isRestructured: { type: DataTypes.BOOLEAN, defaultValue: false },
  parentLoanId: { type: DataTypes.UUID, allowNull: true },
  officerId: { type: DataTypes.UUID, allowNull: true, comment: 'Loan Officer assigned' },
  notes: DataTypes.TEXT,
}, {
  tableName: 'loans',
  paranoid: true,
  indexes: [
    { unique: true, fields: ['organizationId', 'loanNumber'] },
    { fields: ['memberId'] },
    { fields: ['organizationId'] },
    { fields: ['branchId'] },
    { fields: ['status'] },
  ],
});

export const LoanRepayment = sequelize.define('LoanRepayment', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  organizationId: { type: DataTypes.UUID, allowNull: false },
  loanId: { type: DataTypes.UUID, allowNull: false, references: { model: 'loans', key: 'id' } },
  memberId: { type: DataTypes.UUID, allowNull: false },
  reference: { type: DataTypes.STRING(50), allowNull: false, unique: true },
  installmentNumber: DataTypes.INTEGER,
  dueDate: { type: DataTypes.DATEONLY, allowNull: false },
  dueAmount: { type: DataTypes.DECIMAL(15, 2), allowNull: false },
  principalDue: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  interestDue: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  penaltyDue: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  amountPaid: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  principalPaid: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  interestPaid: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  penaltyPaid: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  paymentDate: DataTypes.DATE,
  paymentMethod: DataTypes.ENUM('cash', 'mpesa', 'bank_transfer', 'account_debit'),
  externalReference: DataTypes.STRING(100),
  status: { type: DataTypes.ENUM('pending', 'partial', 'paid', 'overdue'), defaultValue: 'pending' },
  processedBy: DataTypes.UUID,
}, {
  tableName: 'loan_repayments',
  paranoid: false,
  indexes: [{ fields: ['loanId'] }, { fields: ['memberId'] }, { fields: ['dueDate'] }, { fields: ['status'] }],
});

export const Guarantor = sequelize.define('Guarantor', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  organizationId: { type: DataTypes.UUID, allowNull: false },
  loanId: { type: DataTypes.UUID, allowNull: false, references: { model: 'loans', key: 'id' } },
  memberId: { type: DataTypes.UUID, allowNull: false, references: { model: 'members', key: 'id' } },
  amountGuaranteed: { type: DataTypes.DECIMAL(15, 2), allowNull: false },
  remainingLiability: { type: DataTypes.DECIMAL(15, 2), defaultValue: 0 },
  status: { type: DataTypes.ENUM('pending', 'accepted', 'declined', 'released'), defaultValue: 'pending' },
  acceptedAt: DataTypes.DATE,
  releasedAt: DataTypes.DATE,
  releasedBy: DataTypes.UUID,
}, {
  tableName: 'guarantors',
  paranoid: true,
});
